SER-1822 - audit setup
one-acre-fund/oaf--ph-ee-operations-app pull request #6
Opened 2023-08-15 07:49 UTC by Vikeln

Audit functionality created.
An audit event on an entity can be done as show below, called as an application event

Autowire the ApplicationEventPublisher to trigger async events
  ```
  @Autowired
    private ApplicationEventPublisher publisher;
```
create a new audit event and trigger it
  ```
 NewAuditEvent event = new NewAuditEvent(this, 1, "UPDATE", "AppUser", "", "data", currentUser, "SUCCESS");
 publisher.publishEvent(event);
```

2023-08-16 11:29 UTC, amydoxym requested changes

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/api/AuditApiResource.java
> +    @Operation(summary = "List Audits", description = "Get a 200 list of audits that match the criteria supplied and sorted by audit id in descending order, and are within the requestors' data scope.
```suggestion
    @Operation(summary = "List Audits", description = "Get a list of audits that match the criteria supplied and sorted by audit id in descending order, and are within the requestors' data scope. Also it supports pagination and sorting\n" + "\n" + "Example Request:\n" + "\n" + "audits\n" + "\n" + "audits?actionName=UPDATE&entityName=AppUser\n")
```

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/data/AuditSearch.java
> +public class AuditSearch {
add javadoc

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/data/AuditSource.java
> +public class AuditSource extends AbstractPersistableCustom<Long> {
add javadoc

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/data/AuditSource.java
> +    private Date madeOnDate;
please use LocalDate and if possible LocalDateTime to support timezones

 and `@Temporal(TemporalType.TIMESTAMP)` is no longer needed

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/events/NewAuditEvent.java
> +public class NewAuditEvent extends ApplicationEvent {
add javadoc

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/events/AuditEventListener.java
> +public class AuditEventListener {
add javadoc

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/service/AuditServiceImpl.java
> +    public AuditSource createNewEntry(NewAuditEvent event) {
please add @Transactional

2023-08-16 11:29 UTC, amydoxym commented on src/main/java/org/apache/fineract/audit/service/AuditServiceImpl.java
> +    public Page<AuditSource> getAudits(Specification<AuditSource> specification, Pageable pageable) {
Add @Transactional(readOnly=true)

2023-08-31 07:24 UTC, victorjbassey approved these changes

2023-09-11 10:28 UTC, gilclefes approved these changes
looks good to me.

2023-09-15 11:39 UTC, amydoxym approved these changes

2023-09-28 07:05 UTC, merged